import React from "react"
import Header from "./Header"
import MyInfo from "./MyInfo"
import Footer from "./footer"

function App(){
	return(
		<div>
		<Header />
		<MyInfo />
		<input type="checkbox" />
		<p>Placeholder Text</p>

		<input type="checkbox" />
		<p>Placeholder Text</p>

		<input type="checkbox" />
		<p>Placeholder Text</p>

		<input type="checkbox" />
		<p>Placeholder Text</p>

		<input type="checkbox" />
		<p>Placeholder Text</p>

		<input type="checkbox" />
		<p>Placeholder Text</p>
		</Footer>
		</div>
		)
}
export default App